server:
  command: "php psr-worker.php"

http:
  address: 0.0.0.0:8080
  pool:
    num_workers: 4

service:
  cron:
    command: php cron-worker.php
    process_num: 4
    exec_timeout: 0
    remain_after_exit: true
    restart_sec: 1
